# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
# project: w35
queue: express
walltime: 3:00:00
jobname: 1deg_jra55_ryf
ncpus: 252
mem: 500GB

# Force payu to always find, and save, files in this short (or scratch) project directory
# shortpath: /scratch/w35

# Model configuration
name: common
model: access-om2
input: /g/data/ik11/inputs/access-om2/input_236a3011/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /g/data/ik11/inputs/access-om2/bin/yatm_4198e150.exe
      input: 
            - /g/data/ik11/inputs/access-om2/input_236a3011/yatm_1deg
            - /g/data/ua8/JRA55-do/RYF/v1-3/
      ncpus: 1

    - name: ocean
      model: mom
      exe: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM_e837d05d_libaccessom2_4198e150.x
      input: /g/data/ik11/inputs/access-om2/input_236a3011/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /g/data/ik11/inputs/access-om2/bin/cice_auscom_360x300_24p_597e4561_libaccessom2_4198e150.exe
      input: /g/data/ik11/inputs/access-om2/input_236a3011/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
qsub_flags: -W umask=027
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
